spring:
  datasource:
    username: root
    password: rjsgml33
    url: jdbc:mysql://localhost:3309/pers
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
    show_sql: true